openapi: 3.0.0
info:
  title: ShadowGen Web Gateway
  version: 1.0.0
servers:
  - url: https://shadowgen.solofarm.ru
paths:
  /:
    x-yc-apigateway-any-method:
      x-yc-apigateway-integration:
        type: serverless_containers
        container_id: bbac812eou2e620rvdcp
        service_account_id: aje1kqd422vq2vefkbbl
  /{proxy+}:
    x-yc-apigateway-any-method:
      parameters:
        - name: proxy
          in: path
          required: false
          schema:
            type: string
            default: "-"
          style: simple
          explode: false
      x-yc-apigateway-integration:
        type: serverless_containers
        container_id: bbac812eou2e620rvdcp
        service_account_id: aje1kqd422vq2vefkbbl

